apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
metadata:
  name: my-rest-api-component # Component name
  namespace: default # Optional: specify the namespace
spec:
  endpoints:
    - name: "REST API"
      port: 8000
      type: REST
      networkVisibility: Public
      context: /
  containers:
    - name: rest-api-container
      image: my-app-image:latest # Replace with your Docker image
      ports:
        - containerPort: 8000 # Ensure this matches the exposed port
      resources:
        requests:
          cpu: "250m" # Minimum CPU required
          memory: "256Mi" # Minimum memory required
        limits:
          cpu: "500m" # Maximum CPU allowed
          memory: "512Mi" # Maximum memory allowed
  environmentVariables:
    - name: ENVIRONMENT # Set environment variables if needed
      value: production
